export const SEARCH="SEARCH";

export const CARD_IMAGE="CARD_IMAGE";
export const NEWS_SOURCE="NEWS_SOURCE";
export const NEWS_AUTHOR="NEWS_AUTHOR";
export const NEWS_TITLE="NEWS_TITLE";
export const NEWS_DESCRIPTION="NEWS_DESCRIPTION";
export const NEWS_URL="NEWS_URL";
export const NEWS_URL_TO_IMAGE="NEWS_URL_TO_IMAGE";
export const NEWS_PUBLISHEDAT="NEWS_PUBLISHEDAT";
export const NEWS_CONTENT="NEWS_CONTENT";
export const NEWS_STATUS="NEWS_STATUS";
export const NEWS_ERROR_RECEIVE="NEWS_ERROR_RECEIVE";