{ 
    "status": "ok", 
    "totalResults": 5730, 
    "articles": [
        {"source": { "id": null, "name": "Newsbtc.com" }, 
        "author": "Cole Petersen", 
        "title": "History Suggests Bitcoin is Currently in Early Stages of Next Bull Run", 
        "description": "After briefly incurring a significant influx of buying pressure, Bitcoin (BTC) has once again lost its momentum and is now nearing its key psychological support level at $10,000, which has proven to be a strong support level for the cryptocurrency in recent t…", 
        "url": "https://www.newsbtc.com/2019/09/21/history-suggests-bitcoin-is-currently-in-early-stages-of-next-bull-run/", 
        "urlToImage": "https://www.newsbtc.com/wp-content/uploads/2019/09/shutterstock_680368252-4-1200x780.jpg", 
        "publishedAt": "2019-09-21T19:30:51Z", 
        "content": "After briefly incurring a significant influx of buying pressure, Bitcoin (BTC) has once again lost its momentum and is now nearing its key psychological support level at $10,000, which has proven to be a strong support level for the cryptocurrency in recent t… [+2747 chars]" }, 
        { "source": { "id": null, "name": "Sensorstechforum.com" }, 
        "author": "Gergana Ivanova", 
        "title": "Karl File Virus (.karl Ransomware ) – How to Remove It", 
        "description": "The article presents detailed information about Karl virus as well as a step-by-step guide on how to remove associated malicious files from the infected system and how to potentially recover. encrypted files. The name Karl virus is given to a vicious crypto i…", 
        "url": "https://sensorstechforum.com/karl-file-virus-ransomware-remove/", 
        "urlToImage": "https://sensorstechforum.com/wp-content/uploads/2019/09/remove-ransomware-virus-restore-files-sensorstechforum.jpg", 
        "publishedAt": "2019-09-21T18:34:00Z", 
        "content": "The article presents detailed information about Karl virus as well as a step-by-step guide on how to remove associated malicious files from the infected system and how to potentially recover . encrypted files.\r\nThe name Karl virus is given to a vicious crypto… [+23753 chars]" }, 
        { "source": { "id": null, "name": "Newsbtc.com" }, 
        "author": "Nick Chong", 
        "title": "Ethereum Price in Precarious Situation, Pullback Likely; Here’s Why", 
        "description": "After months of lull, Ethereum (ETH) has entered the consciousness of crypto traders once again, finding its legs for really the first time this year. Since hitting $170 in early-September, the cryptocurrency has rocketed higher to peak at $225, to then reced…", 
        "url": "https://www.newsbtc.com/2019/09/21/ethereum-price-precarious-situation-pullback-heres-why/", 
        "urlToImage": "https://www.newsbtc.com/wp-content/uploads/2019/09/shutterstock_533153143-1200x780.jpg", 
        "publishedAt": "2019-09-21T18:00:57Z", 
        "content": "After months of lull, Ethereum (ETH) has entered the consciousness of crypto traders once again, finding its legs for really the first time this year. Since hitting $170 in early-September, the cryptocurrency has rocketed higher to peak at $225, to then reced… [+2550 chars]" }, 
        { "source": { "id": null, "name": "Bitcoinist.com" }, 
        "author": "Julio Gil-Pulgar", 
        "title": "Lawsuit to Abolish BitLicense Moving to Highest NY Court", 
        "description": "Theo Chino and his attorney Pierre Ciric have been trying to eliminate BitLicense almost since its enactment. Now they are pushing their case to The New York Court of Appeals, which is the highest court in the state of New York. BitLicense Is Onerous and Too …", 
        "url": "https://bitcoinist.com/lawsuit-to-abolish-bitlicense-moving-to-highest-ny-court/", 
        "urlToImage": "https://bitcoinist.com/wp-content/uploads/2019/05/shutterstock_772822198.png", 
        "publishedAt": "2019-09-21T17:57:25Z", 
        "content": "Theo Chino and his attorney Pierre Ciric have been trying to eliminate BitLicense almost since its enactment. Now they are pushing their case to The New York Court of Appeals, which is the highest court in the state of New York.\r\nBitLicense Is Onerous and Too… [+3003 chars]" }, 
        { "source": { "id": null, "name": "Expressen.se" }, 
        "author": "mattias.tengblad@expressen.se (Mattias Tengblad)", 
        "title": "Utsätts för bedrägeri: ”Det här är olagligt”", 
        "description": "Manchester Uniteds tränare Ole Gunnar Solkskjaer har blivit utsatt för bedrägeri. Nu har han kopplat in sina advokater. I en fejkad annons, där även Fredrik Skavlan finns med, påstås det att norrmannen tjänat miljontals kronor på ett tvivelaktigt sätt. – Det …", 
        "url": "https://www.expressen.se/sport/fotboll/premier-league/utnyttjas-i-reklam-det-har-ar-olagligt/", 
        "urlToImage": "https://x.cdn-expressen.se/images/25/a1/25a1a27f3be3432e9734d60319558d5a/16x9/original.jpg", 
        "publishedAt": "2019-09-21T17:40:40Z", 
        "content": "Det är den norska tidningen Dagbladet, som även de blivit utsatta, som skriver om händelsen.\r\nNågon har på sociala medier använt Dagbladets logga i en fejkad annons med Ole Gunnar Solskjaer, där även tv-profilen Fredrik Skavlan finns med på bild, där man påst… [+1238 chars]" }, 
        { "source": { "id": null, "name": "Cointelegraph.com" }, 
        "author": "Cointelegraph By Helen Partz", 
        "title": "Bitcoin’s Dominance Drops as BTC Price Briefly Dips Below $10K",
         "description": "Crypto markets continue to trade sideways, with the majority of the top 20 coins by market cap seeing losses", 
        "url": "https://cointelegraph.com/news/bitcoins-dominance-drops-as-btc-price-briefly-dips-below-10k", 
        "urlToImage": "https://images.cointelegraph.com/images/740_aHR0cHM6Ly9zMy5jb2ludGVsZWdyYXBoLmNvbS9zdG9yYWdlL3VwbG9hZHMvdmlldy82ZTg3M2VlZDQzMGYzZGZmOGI0MTFkODZhYTc5OGJjZC5qcGc=.jpg", 
        "publishedAt": "2019-09-21T16:41:00Z", 
        "content": "Saturday, Sept. 21 — crypto markets continued to trade sideways, with the majority of the top 20 coins by market cap seeing losses at press time.\r\nMarket visualization. Source: Coin360\r\nBitcoin dominance continues to slip\r\nAfter briefly dipping below $10,000 … [+2064 chars]" }, 
        { "source": { "id": null, "name": "Cointelegraph.com" }, 
        "author": "Cointelegraph By Alexander Kanen", 
        "title": "Real Estate, Blockchain and the Quantity Theory of Money", 
        "description": "Exploring the quantity theory of money and the effect tokenization could have on future demand for commercial real estate investments.", 
        "url": "https://cointelegraph.com/news/tokenizing-commercial-real-estate-and-promise-of-liquidity", 
        "urlToImage": "https://images.cointelegraph.com/images/740_aHR0cHM6Ly9zMy5jb2ludGVsZWdyYXBoLmNvbS9zdG9yYWdlL3VwbG9hZHMvdmlldy9kOTc4Y2Q4NGRmZjU0ZDYzNWE0MjFjYmEyMGRkYjI3My5qcGc=.jpg", 
        "publishedAt": "2019-09-21T16:10:00Z", 
        "content": "The concept of illiquidity discounts, how it relates to markets like commercial real estate, and the benefits that tokenization could bring to the industry are topics that I have already discussed in previous articles. In this article, I am taking a closer lo… [+10956 chars]" }, 
        { "source": { "id": null, "name": "Adslzone.net" }, 
        "author": "Rocío García", 
        "title": "Las mejores series de robots y tecnología en Netflix y otras plataformas", 
        "description": "Si alguna vez has dicho que eres informático y te han puesto a arreglar la lavadora, te sentirás identificado. Las mejores series de robots y mejores series de tecnología con todo tipo de argumentos: ciencia ficción, efectos especiales u oficinas en el sótano…", 
        "url": "https://www.adslzone.net/reportajes/series/mejores-series-robots-tecnologia/", 
        "urlToImage": "https://www.adslzone.net/app/uploads/2019/09/Mejores-series-de-robots-y-tecnología.jpg", 
        "publishedAt": "2019-09-21T16:00:21Z", 
        "content": "Si alguna vez has dicho que eres informático y te han puesto a arreglar la lavadora, te sentirás identificado. Las mejores series de robots y mejores series de tecnología con todo tipo de argumentos: ciencia ficción, efectos especiales u oficinas en el sótano… [+12610 chars]" }, 
        { "source": { "id": null, "name": "Meneame.net" }, 
        "author": "Romerales", 
        "title": "Bakkt anuncia una póliza de seguro masiva de 125 millones de dólares para depósitos de Bitcoin", 
        "description": "Bitcoin Noticias Bakkt anuncia una póliza de seguro masiva de USD $ 125 millones para depósitos de Bitcoin Haz clic para compartir en Twitter (Se abre en una ventana nueva)Haz clic para compartir en Facebook (Se abre en una ventana nueva)Haz clic para compart…", 
        "url": "https://www.meneame.net/m/tecnología/bakkt-anuncia-poliza-seguro-masiva-125-millones-dolares-bitcoin", 
        "urlToImage": "https://www.meneame.net//mnmstatic.net/img/mnm/logo-350x350.png", 
        "publishedAt": "2019-09-21T15:48:43Z", 
        "content": null }, 
        { "source": { "id": null, "name": "Brica.de" }, 
        "author": "", 
        "title": "Russian Cybercrime Group FullofDeep Behind QNAPCrypt Ransomware Campaigns", 
        "description": "We previously reported on how we managed to temporarily shut down 15 operative QNAPCrypt ransomware campaigns targeting Linux-based file storage systems (NAS servers). We have now identified a new QNAPCrypt sample which is being used by the same threat actor …", 
        "url": "https://brica.de/alerts/alert/public/1277585/russian-cybercrime-group-fullofdeep-behind-qnapcrypt-ransomware-campaigns/", 
        "urlToImage": null, 
        "publishedAt": "2019-09-21T15:40:00Z", 
        "content": "We previously reported on how we managed to temporarily shut down 15 operative QNAPCrypt ransomware campaigns targeting Linux-based file storage systems (NAS servers). We have now identified a new QNAPCrypt sample which is being used by the same threat actor … [+3376 chars]" }, 
        { "source": { "id": null, "name": "Yahoo.com" }, 
        "author": "Jose Antonio Lanz", 
        "title": "Colombia is slowly moving toward Bitcoin-friendly regulations", 
        "description": "Cryptocurrencies operate in murky legal territory in Colombia. But a determined congressman from Bogotá aims to drag the industry into the light.", 
        "url": "https://finance.yahoo.com/news/colombia-slowly-moving-toward-bitcoin-223024164.html", 
        "urlToImage": "https://s.yimg.com/ny/api/res/1.2/U4gdSU2QA_rVHrV7IEGOrw--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyODA7aD02NjguNDQ0NDQ0NDQ0NDQ0NQ--/https://s.yimg.com/uu/api/res/1.2/UHsy5pbprsCcfknkVTJnjw--~B/aD00NzA7dz05MDA7c209MTthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/decrypt_251/2474b14577a1568be53f8429cc5ab876", 
        "publishedAt": "2019-09-21T14:00:40Z", 
        "content": "To say Colombia doesnt have the bestcryptocurrency regulations in the world would be an understatement. As it stands, crypto, and those who operate in it, have no legal status or protection in the country.\r\nBut a new breed of Colombian lawmakers are working h… [+6474 chars]" }, 
        { "source": { "id": null, "name": "Harvard.edu" }, 
        "author": null, 
        "title": "Trading and Arbitrage in Cryptocurrency Markets", 
        "description": "Cryptocurrencies such as bitcoin or ethereum have rocketed to public attention over the past few years. These are digital currencies built on blockchain technology that allows verification of payments and other transactions in the absence of a centralized cus…", 
        "url": "https://corpgov.law.harvard.edu/2019/09/21/trading-and-arbitrage-in-cryptocurrency-markets/", 
        "urlToImage": null, 
        "publishedAt": "2019-09-21T13:16:18Z", 
        "content": "Igor Makarov is Associate Professor of Finance at the London School of Economics and Political Science and Antoinette Schoar is the Michael M. Koerner Professor of Entrepreneurship at the MIT Sloan School of Management. This post is based on their recent arti… [+7343 chars]" }, 
        { "source": { "id": null, "name": "Bitcoinmagazine.com" }, 
        "author": "Giacomo Zucco", 
        "title": "Discovering Bitcoin Part 6: Digital Contracts", 
        "description": "In the sixth installment of Giacomo Zucco’s “Discovering Bitcoin” series, he explores concepts of proving ownership, smart contracts and CoinJoins. The post Discovering Bitcoin Part 6: Digital Contracts appeared first on Bitcoin Magazine.", 
        "url": "https://bitcoinmagazine.com/articles/discovering-bitcoin-part-6-digital-contracts?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+BitcoinMagazine+%28Bitcoin+Magazine%29", 
        "urlToImage": null, 
        "publishedAt": "2019-09-21T13:00:15Z", 
        "content": null }, 
        { "source": { "id": null, "name": "Forbes.com" }, 
        "author": "Billy Bambrough", 
        "title": "Bitcoin And Crypto Wallets Are Now Being Targeted By Malware", 
        "description": "came along with Now, cyber security researchers have warned that malware could be stealing bitcoin and cryptocurrency wallet information. Increased bitcoin awareness, coupled with the sudden rise in the value of bitcoin and other cryptocurrencies, means that …", 
        "url": "https://www.forbes.com/sites/billybambrough/2019/09/19/bitcoin-and-crypto-wallets-now-targeted-by-malware/", 
        "urlToImage": "https://thumbor.forbes.com/thumbor/600x315/https%3A%2F%2Fspecials-images.forbesimg.com%2Fimageserve%2F1158187867%2F960x0.jpg", 
        "publishedAt": "2019-09-21T12:59:00Z", 
        "content": "Bitcoin and the wider cryptocurrency market's huge price rise over the last few years meant that criminals quickly began taking a closer interest in crypto. A rapid increase in crypto scams and thefts came along with mainstream bitcoin awareness.\r\nNow, cyber … [+4432 chars]" }, 
        { "source": { "id": null, "name": "Bitcoinmagazine.com" }, 
        "author": "Colin Harper", 
        "title": "The Fed Just Pumped $278 Billion Into the U.S. Economy: Here’s How", 
        "description": "The New York branch of the Federal Reserve just financed $278 billion worth of repurchasing agreements, an echo to the Great Recession. The post The Fed Just Pumped $278 Billion Into the U.S. Economy: Here’s How appeared first on Bitcoin Magazine.", 
        "url": "https://bitcoinmagazine.com/articles/the-fed-just-pumped-278-billion-into-the-u-s-economy-heres-how?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+BitcoinMagazine+%28Bitcoin+Magazine%29", 
        "urlToImage": null, 
        "publishedAt": "2019-09-21T12:45:32Z", 
        "content": null }, 
        { "source": { "id": null, "name": "Wykop.pl" }, 
        "author": "szabo", 
        "title": "Inwestowanie w kryptowaluty. Jak zacząć, czy to się opłaca?", 
        "description": "W ostatnim czasie coraz popularniejszym sposobem na inwestowanie pieniędzy są kryptowaluty, wśród których najbardziej znany stał się Bitcoin. Choć początkowo stanowił niszowe rozwiązanie dla osób poszukujących alternatyw wobec tradycyjnego systemu finansowego…", 
        "url": "https://www.wykop.pl/link/5140263/inwestowanie-w-kryptowaluty-jak-zaczac-czy-to-sie-oplaca/", 
        "urlToImage": "https://www.wykop.pl/cdn/c3397993/link_QLjTxWXMf4ChS0Phn2fLbYjICkrm6OHS,w1200h627.jpg", 
        "publishedAt": "2019-09-21T12:36:12Z", 
        "content": "Drogi Wykopowiczu\r\nw zaczonym linku do Polityki Prywatnoci przypominamy podstawowe informacje z zakresu przetwarzania danych osobowych dostarczanych przez Ciebie podczas korzystania z naszego serwisu. Zamykajc ten komunikat (klikajc w przycisk X), potwierdzas… [+48 chars]" }, 
        { "source": { "id": null, "name": "Slashdot.org" }, "author": "jackkennion", 
        "title": "Visit BTC News Feed And Get Latest Updated Stories Here", 
        "description": "Know the real-time market news, bitcoin updates, and various other trading updates on Bitcoin News. Read  BTC News  daily to keep yourself updated with the market.", 
        "url": "https://slashdot.org/submission/10409396/visit-btc-news-feed-and-get-latest-updated-stories-here", 
        "urlToImage": null, 
        "publishedAt": "2019-09-21T12:32:04Z", 
        "content": "The Fine Print: The following comments are owned by whoever posted them. We are not responsible for them in any way." }, 
        { "source": { "id": null, "name": "Bitcoinist.com" }, 
        "author": "Osato Avan-Nomayo", 
        "title": "Bitcoin (BTC) Interest in China Driven by Price Action News", 
        "description": "Baidu search trends in 2019 show Chinese bitcoin interest being driven largely by price action news. Meanwhile, ‘BTC’ has become a more popular search term than ‘bitcoin’ according to data from Google Trends. Chinese Bitcoin Interest is News Driven Tweeting o…", 
        "url": "https://bitcoinist.com/baidu-btc-bitcoin-interest-in-china-driven-by-price/", 
        "urlToImage": "https://bitcoinist.com/wp-content/uploads/2019/06/shutterstock_1272415192.png", 
        "publishedAt": "2019-09-21T12:31:09Z", 
        "content": "Baidu search trends in 2019 show Chinese bitcoin interest being driven largely by price action news. Meanwhile, BTC has become a more popular search term than bitcoin according to data from Google Trends.\r\nChinese Bitcoin Interest is News Driven\r\nTweeting on … [+2491 chars]" }, 
        { "source": { "id": null, "name": "Techtimes.com" }, 
        "author": "Allan Adamson", 
        "title": "Malware InnfiRAT Targets Bitcoin And Crypto Wallets", 
        "description": "The malware named InnfiRAT could be stealing bitcoins and cryptocurrency wallet information. It is usually downloaded through email attachments and apps, so the first line of defense is to avoid programs and attachments that are not from trusted sources.", 
        "url": "https://www.techtimes.com/articles/245418/20190921/malware-innfirat-targets-bitcoin-and-crypto-wallets.htm", 
        "urlToImage": "https://1734811051.rsc.cdn77.org/data/images/full/357793/computer.jpg", 
        "publishedAt": "2019-09-21T12:10:00Z", 
        "content": "The increasing popularity and value of Bitcoin and other cryptocurrencies has not gone unnoticed by scammers and other criminals.\r\nMalware InnfiRAT Can Steal Cryptocurrency Wallet Data\r\nThe number of crypto-related scams and thefts have increased over the las… [+1956 chars]" }, 
        { "source": { "id": null, "name": "Bitcoinmagazine.com" }, 
        "author": "Jimmy Aki", 
        "title": "Bitcoin Magazine Week in Review", 
        "description": "Bitcoin Magazine’s Week in Review brings you the most critical, interesting and popular news stories affecting Bitcoin this week. The post Bitcoin Magazine Week in Review appeared first on Bitcoin Magazine.", 
        "url": "https://bitcoinmagazine.com/articles/bitcoin-magazine-week-in-review?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+BitcoinMagazine+%28Bitcoin+Magazine%29", 
        "urlToImage": null, 
        "publishedAt": "2019-09-21T12:00:52Z", 
        "content": null }
    ]
 }